function results = runExercise2(baseMarket, settings)
%RUNEXERCISE2 Price and validate the 10Y Bermudan payer swaption.

    marketIR = baseMarket;

    %% Initialize Bermudan contract

    Bermudan = initializeExercise2Bermudan( ...
        marketIR);

    %% Build Hull-White tree

    [treeHullWhite, probabilities] = initializeExercise2HullWhiteTree( ...
        Bermudan, ...
        settings.hullWhite);

    %% Build discount factors for tree dates and contractual payment dates

    [B0Tree, treeDates, treeTimes, B0Payments, paymentDates, ...
        paymentTimes, deltaPayments] = buildBermudanDiscountFactors( ...
            marketIR, ...
            treeHullWhite, ...
            Bermudan);

    %% Price Bermudan payer swaption

    bermudanSwaptionPrice = bermudanSwaptionTreePricer( ...
        treeHullWhite, ...
        probabilities, ...
        Bermudan, ...
        paymentTimes, ...
        deltaPayments, ...
        B0Tree, ...
        B0Payments);

    printExercise2PriceReport( ...
        bermudanSwaptionPrice);

    %% Tree diagnostics

    diagnostics = checkHullWhiteTreeProbabilitiesAndMoments( ...
        treeHullWhite, ...
        probabilities);

    %% ZCB and European swaption validation

    zcbMaturities = [1; 2; 3; 5; 7; 10];

    europeanExpiries = [2; 3; 4; 5; 6; 7; 8; 9];

    comparison = compareHullWhiteTreeBenchmarks( ...
        treeHullWhite, ...
        probabilities, ...
        Bermudan, ...
        paymentTimes, ...
        deltaPayments, ...
        B0Tree, ...
        B0Payments, ...
        zcbMaturities, ...
        europeanExpiries);

    plotHullWhiteBenchmarkErrors( ...
        comparison);

    %% Bounds

    bounds = computeBermudanSwaptionBounds( ...
        marketIR, ...
        treeHullWhite, ...
        Bermudan, ...
        paymentTimes, ...
        deltaPayments, ...
        B0Tree, ...
        B0Payments, ...
        bermudanSwaptionPrice);

    printExercise2BoundsSummary( ...
        bounds);

    %% Store results

    results = struct();

    results.marketIR = marketIR;
    results.Bermudan = Bermudan;

    results.treeHullWhite = treeHullWhite;
    results.probabilities = probabilities;

    results.B0Tree = B0Tree;
    results.treeDates = treeDates;
    results.treeTimes = treeTimes;

    results.B0Payments = B0Payments;
    results.paymentDates = paymentDates;
    results.paymentTimes = paymentTimes;
    results.deltaPayments = deltaPayments;

    results.price = bermudanSwaptionPrice;
    results.diagnostics = diagnostics;
    results.comparison = comparison;
    results.bounds = bounds;

end