function results = runExercise1b(baseMarket, product, results1a, settings)
%RUNEXERCISE1B Price the base product under alternative models.
%
%   Alternative models:
%       1. Variance Gamma
%       2. Black without smile correction
%       3. Black with smile correction

    nSim = settings.nSim;
    rngSeed = settings.rngSeed;

    marketNIG = results1a.marketNIG;
    upfrontNIG = results1a.upfrontNIG;
    legA_NIG = results1a.legA_NIG;
    legB_NIG = results1a.legB_NIG;

    %% ================================================================
    %  Variance Gamma pricing
    % ================================================================

    marketVG = baseMarket;

    marketVG = calibrateVG( ...
        marketVG, ...
        product);

    marketVG.vg.alpha = 0;
    marketVG.vg.modelName = 'VG';

    marketVG.simulation = simulateEarlyRedemptionVG( ...
        product, ...
        marketVG, ...
        nSim, ...
        rngSeed);

    marketVG.simulation.modelName = "VG";

    [upfrontVG, mtmA_VG, legA_VG, legB_VG] = computeUpfront( ...
        marketVG, ...
        product);

    printPricingReport( ...
        marketVG, ...
        product, ...
        upfrontVG, ...
        mtmA_VG, ...
        legA_VG, ...
        legB_VG);

    %% ================================================================
    %  Black without smile correction
    % ================================================================

    marketBlack = marketNIG;

    marketBlack.nts.modelName = 'Black';

    marketBlack.simulation = simulateEarlyRedemptionEventBlack( ...
        product, ...
        marketBlack, ...
        "Black");

    marketBlack.simulation.modelName = "Black";

    [upfrontBlack, mtmA_Black, legA_Black, legB_Black] = computeUpfront( ...
        marketBlack, ...
        product);

    printPricingReport( ...
        marketBlack, ...
        product, ...
        upfrontBlack, ...
        mtmA_Black, ...
        legA_Black, ...
        legB_Black);

    %% ================================================================
    %  Black with smile correction
    % ================================================================

    marketBlackCorrected = marketNIG;

    marketBlackCorrected.nts.modelName = 'BlackCorrected';

    marketBlackCorrected.simulation = simulateEarlyRedemptionEventBlack( ...
        product, ...
        marketBlackCorrected, ...
        "BlackCorrected");

    marketBlackCorrected.simulation.modelName = "BlackCorrected";

    [upfrontBlackCorrected, mtmA_BlackCorrected, ...
        legA_BlackCorrected, legB_BlackCorrected] = computeUpfront( ...
            marketBlackCorrected, ...
            product);

    printPricingReport( ...
        marketBlackCorrected, ...
        product, ...
        upfrontBlackCorrected, ...
        mtmA_BlackCorrected, ...
        legA_BlackCorrected, ...
        legB_BlackCorrected);

    %% Black comparison report

    printBlackModelSelectionReport( ...
        product, ...
        marketBlack, ...
        upfrontBlack, ...
        mtmA_Black, ...
        legA_Black, ...
        legB_Black, ...
        marketBlackCorrected, ...
        upfrontBlackCorrected, ...
        mtmA_BlackCorrected, ...
        legA_BlackCorrected, ...
        legB_BlackCorrected);

    %% Model selection summary

    printModelSelectionSummary( ...
        marketNIG, ...
        upfrontNIG, ...
        legA_NIG, ...
        legB_NIG, ...
        marketVG, ...
        upfrontVG, ...
        legA_VG, ...
        legB_VG, ...
        marketBlack, ...
        upfrontBlack, ...
        legA_Black, ...
        legB_Black, ...
        marketBlackCorrected, ...
        upfrontBlackCorrected, ...
        legA_BlackCorrected, ...
        legB_BlackCorrected);

    %% Store results

    results = struct();

    results.marketVG = marketVG;
    results.upfrontVG = upfrontVG;
    results.mtmA_VG = mtmA_VG;
    results.legA_VG = legA_VG;
    results.legB_VG = legB_VG;

    results.marketBlack = marketBlack;
    results.upfrontBlack = upfrontBlack;
    results.mtmA_Black = mtmA_Black;
    results.legA_Black = legA_Black;
    results.legB_Black = legB_Black;

    results.marketBlackCorrected = marketBlackCorrected;
    results.upfrontBlackCorrected = upfrontBlackCorrected;
    results.mtmA_BlackCorrected = mtmA_BlackCorrected;
    results.legA_BlackCorrected = legA_BlackCorrected;
    results.legB_BlackCorrected = legB_BlackCorrected;

end