function printModelSelectionSummary( ...
    marketNIG, upfrontNIG, legA_NIG, legB_NIG, ...
    marketVG, upfrontVG, legA_VG, legB_VG, ...
    marketBlack, upfrontBlack, legA_Black, legB_Black, ...
    marketBlackCorrected, upfrontBlackCorrected, ...
    legA_BlackCorrected, legB_BlackCorrected)
%PRINTMODELSELECTIONSUMMARY Print Exercise 1.b model selection summary.

    fprintf('\n============================================================\n');
    fprintf(' ASSIGNMENT 6 - MODEL SELECTION SUMMARY\n');
    fprintf('============================================================\n');

    fprintf('\n%-22s %-18s %-18s %-18s %-18s\n', ...
        'Model', 'P(ER)', 'LegA NPV', 'LegB NPV', 'Upfront');
    fprintf('%s\n', repmat('-', 1, 100));

    fprintf('%-22s %-18.10f %-18.10f %-18.10f %-18.10f\n', ...
        'NIG', ...
        marketNIG.simulation.probabilityEarlyRedemption, ...
        legA_NIG.npv, ...
        legB_NIG.npv, ...
        upfrontNIG);

    fprintf('%-22s %-18.10f %-18.10f %-18.10f %-18.10f\n', ...
        'VG', ...
        marketVG.simulation.probabilityEarlyRedemption, ...
        legA_VG.npv, ...
        legB_VG.npv, ...
        upfrontVG);

    fprintf('%-22s %-18.10f %-18.10f %-18.10f %-18.10f\n', ...
        'Black', ...
        marketBlack.simulation.probabilityEarlyRedemption, ...
        legA_Black.npv, ...
        legB_Black.npv, ...
        upfrontBlack);

    fprintf('%-22s %-18.10f %-18.10f %-18.10f %-18.10f\n', ...
        'Black corrected', ...
        marketBlackCorrected.simulation.probabilityEarlyRedemption, ...
        legA_BlackCorrected.npv, ...
        legB_BlackCorrected.npv, ...
        upfrontBlackCorrected);

    fprintf('\nDifferences vs NIG\n');

    fprintf('VG - NIG upfront              : %.10f | %.8f%% | %.4f bps\n', ...
        upfrontVG - upfrontNIG, ...
        100 * (upfrontVG - upfrontNIG), ...
        10000 * (upfrontVG - upfrontNIG));

    fprintf('Black - NIG upfront           : %.10f | %.8f%% | %.4f bps\n', ...
        upfrontBlack - upfrontNIG, ...
        100 * (upfrontBlack - upfrontNIG), ...
        10000 * (upfrontBlack - upfrontNIG));

    fprintf('Black corr - NIG upfront      : %.10f | %.8f%% | %.4f bps\n', ...
        upfrontBlackCorrected - upfrontNIG, ...
        100 * (upfrontBlackCorrected - upfrontNIG), ...
        10000 * (upfrontBlackCorrected - upfrontNIG));

    fprintf('============================================================\n');

end