function [treeHullWhite, probabilities] = initializeExercise2HullWhiteTree( ...
    Bermudan, hullWhiteSettings)
%INITIALIZEEXERCISE2HULLWHITETREE Build Hull-White tree and probabilities.

    a = hullWhiteSettings.a;
    sigma = hullWhiteSettings.sigma;
    nStepsPerYear = hullWhiteSettings.nStepsPerYear;

    geometry = buildHullWhiteGeometry( ...
        a, ...
        sigma, ...
        nStepsPerYear);

    treePricer = buildTreePricer( ...
        Bermudan.maturity, ...
        nStepsPerYear, ...
        geometry.lMax, ...
        geometry.dx);

    treeHullWhite = buildHullWhiteTree( ...
        treePricer, ...
        geometry, ...
        a, ...
        sigma);

    probabilities = buildHullWhiteProbabilities( ...
        treeHullWhite);

end